debug: false
after_startup: ""
before_shutdown: "echo 'add cleanup here'"
project:
  name: "corsair"
  path: "."
  environment: "development"
commands:
  - name: "configure"
    command: ""
  - name: "build"
    command: ""
  - name: "test"
    command: ""
  - name: "install"
    command: ""
  - name: "clean"
    command: ""
  - name: "package"
    command: ""
  - name: "benchmark"
    command: ""
  - name: "publish"
    command: ""
watch:
  enabled: true
  hooks:
    - paths: ["./src/corsair", "./src/plugins"]
      recursive: true
      extensions: ["go", "html", "css", "js"]
      command: "go build"
    - paths: ["."]
      recursive: false
      extensions: ["go", "html", "css", "js"]
      command: "go build"
web_ui:
  enabled: true
  api_version: "1"
  host: "localhost"
  port: "8080"
