verbosity: 1
quiet: false
max_cpu: "100%"
log_path: "./corsair.all.log"
pid_path: "./corsair.pid"
server_type: "http"
server_token: "nginx"
databases:
  memory_database:
    enabled: true
plugins:
  - name: "corsair-search"
    enabled: true
    import_path: "plugins/corsair-search"
    repository: ""
    directive:
      name: "search"
      weight: 9000
  - name: "boilerplate"
    enabled: true
    import_path: "plugins/boilerplate"
    repository: ""
    directive:
      name: "boilerplate"
      weight: 9999
