debug: false
quiet: false
max_cpu: "100%"
log_path: "./corsair.all.log"
pid_path: "./corsair.pid"
server:
  server_type: "http"
  user_agent: "nginx"
databases:
  memory_database:
    enabled: true
plugins:
  - name: "corsair-search"
    import_path: "plugins/corsair-search"
    repository: ""
    enabled: true
    directive:
      name: "search"
      weight: 9000
  - name: "boilerplate"
    import_path: "plugins/boilerplate"
    repository: ""
    enabled: true
    directive:
      name: "boilerplate"
      weight: 9999
